export const UPDATE_MOVIES_OBJECT = 'UPDATE_MOVIES_OBJECT';
export const UPDATE_MOVIES = 'UPDATE_MOVIES';
export const UPDATE_SELECTED = 'UPDATE_SELECTED';
export const UPDATE_FETCHING = 'UPDATE_FETCHING';
